### ISSUE TITLE
Coveralls coverage badge fails

### ISSUE THREAD

**Issue by CunliangGeng** [DeepRank/GraphProt#26]
@manonreau The `Coveralls` coverage badge fails, the reason is that the Github action does not send the `pytest` coverage report to `coveralls`.

It might be solved by adding one more action after test, see an example for what I used for DeepRank:
```
    - name: Test with pytest
      run: |
        pytest --cov=deeprank --cov-report xml:coverage.xml
    - name: Coveralls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coverall
```
